---
- name: Deploy Django project
  hosts: all
  vars:
    celery_user: "celery"
    celery_group: "celery"
    github_repo: https://github.com/sempedia/distributed-django-iot.git
  roles:
    # call the clone_repo role: ansible\roles\clone_repo\tasks\main.yaml
    - clone_repo
    # call the services_config role: ansible\roles\services-config
    - services_config
  # add a task to install the redis CLI so we can connect to redis
  # and do a redis ping and to get a redis pong 
  tasks:
    - name: Install Redis CLI
      apt:
        name: redis-tools
        state: present
        update_cache: yes
      become: yes
      
# deploy redis which is only on our main host 
- name: Deploy Redis
  hosts: main
  roles:
    - redis